name: NeteaseCloudMusicAPI Docker Build & Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (for env only)
        uses: actions/checkout@v4

      - name: Clone NeteaseCloudMusicApiReborn API
        run: |
          git clone https://github.com/NeteaseCloudMusicApiReborn/api.git
          cd api
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Replace Dockerfile with optimized version
        run: |
          cat <<EOF > api/Dockerfile
          FROM node:lts-alpine

          RUN apk add --no-cache tini

          WORKDIR /app

          COPY . .

          RUN npm install -g pnpm
          RUN pnpm install

          EXPOSE 3000

          ENTRYPOINT ["/sbin/tini", "--"]

          CMD ["node", "app.js"]
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image (multi-platform)
        uses: docker/build-push-action@v5
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            wudiming/apincm:latest
            wudiming/apincm:${{ env.COMMIT_SHA }}
